language: generic

os:
  - osx
  - linux

sudo:
  - true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pyenv update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pyenv install 3.7.4; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pyenv global 3.7.4; fi


script:
  - python3 --version
  - pip3 install -r requirements.txt
  - pyinstaller -F --hidden-import=utils do
