language: generic

os:
  - osx


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python@3.7.4; fi

script:
  - python --version
  - pip install -r requirements.txt
  - pyinstaller -F --hidden-import=utils do
