version: 2
jobs:
  build:
    macos:
      xcode: 10.0.0
    steps:
      - checkout
      - run:
        name: Install Python
        command: |
          brew install python@3.7.4
          pip install -r requirements.txt
          pyinstaller -F --hidden-import=utils do
