name: Test

on: [push, pull_request]

jobs:
  Testing:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Test
      run: |
        make test

  Linux:
    name: Build [Linux]
    runs-on: ubuntu-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        make clean build

  MacOS:
    name: Build [MacOS]
    runs-on: macos-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        make clean build

  Windows:
    name: Build [Windows]
    runs-on: windows-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        make clean build
