name: Tests

on: [push, pull_request]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Test
        run: |
          make test

	Linux-Build:
		runs-on: ubuntu-latest
		needs: Testing
		steps:
		- uses: actions/checkout@v1
		- name: Get tag
			id: tag
			run: |
				echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
		- name: Set up Python
			uses: actions/setup-python@v1
			with:
				python-version: 3.7
		- name: Install python dependencies
			run: |
				pip install -r requirements.txt
		- name: Build
			run: |
				make clean build
		- name: Upload release file
			uses: actions/upload-artifact@v1
			with:
				name: do-${{ steps.tag.outputs.tag }}-Linux
				path: dist/do

	MacOS-Build:
		runs-on: macos-latest
		needs: Testing
		steps:
		- uses: actions/checkout@v1
		- name: Get tag
			id: tag
			run: |
				echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
		- name: Set up Python
			uses: actions/setup-python@v1
			with:
				python-version: 3.7
		- name: Install python dependencies
			run: |
				pip install -r requirements.txt
		- name: Build
			run: |
				make clean build
		- name: Upload release file
			uses: actions/upload-artifact@v1
			with:
				name: do-${{ steps.tag.outputs.tag }}-Darwin
				path: dist/do

