name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        ./build.sh
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: do-${{ steps.tag.outputs.tag }}-Linux
        path: dist/do

  MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        ./build.sh
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: do-${{ steps.tag.outputs.tag }}-Darwin
        path: dist/do
